language: java

env: 
  - TARGET=neko
  
before_install:
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  - mkdir ~/haxelib
  - haxelib -notimeout setup ~/haxelib 
  - haxelib -notimeout install munit
  - haxelib -notimeout install lime > /dev/null
  - haxelib -notimeout run lime install openfl > /dev/null
  - haxelib -notimeout install systools
  - haxelib git pathfinding https://github.com:Partysun/hxpathfinding.git

script:
  - cd ./tests
  - /bin/sh test.sh
